rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

before_script:
  - "bundle exec rake test_app"

script: "DISPLAY=:99.0 bundle exec rake"

notifications:
  email: false
  irc: "irc.freenode.org#spree_warehouse"
branches:
  only:
    - master
